Repository PeopleForBikes/bna-dashboard, pull requests merged in 2024-03, with the labels that each got.

#1 Adjust environment variables
  next.config.mjs
  src/app/dashboard/new-analysis/action.ts
  src/app/dashboard/results/page.tsx
  src/components/AmplifyAuth/index.tsx
Labels: size/L

#2 initial setup from forked repo
  .eslintrc.js
  .gitignore
  .nvmrc
  next.config.mjs
  package.json
  pnpm-lock.yaml
  requests.rest
  src/app/dashboard/new-analysis/action.ts
  src/app/dashboard/results/page.tsx
  src/app/dashboard/submissions/index.tsx
  src/app/not-found.tsx
  src/aws-exports.js
  src/components/AmplifyAuth/index.tsx
  src/components/Icons/BNALogo/index.tsx
  src/components/Icons/LogoBNALight/index.tsx
  src/components/Icons/ObjectsColumn/index.tsx
  src/components/Icons/School/index.tsx
  src/components/Icons/Store/index.tsx
  src/components/Icons/TrainSubway/index.tsx
  src/components/Icons/Tree/index.tsx
  src/components/Icons/Xmark/index.tsx
Labels: size/XXL

#4 update packages; add info log
  package.json
  pnpm-lock.yaml
  src/app/not-found.tsx
Labels: size/XS

#5 Hotfix
  next.config.mjs
Labels: size/XS

#6 Hotfix
  package.json
  pnpm-lock.yaml
Labels: size/S

#7 trim config file
  next.config.mjs
Labels: size/M

#8 add few more config keys
  next.config.mjs
Labels: size/S

#9 leave out turbotrace config
  next.config.mjs
Labels: size/S

#10 log and render empty when fetch call fails
  src/app/dashboard/submissions/page.tsx
  src/app/not-found.tsx
Labels: size/S

#11 Configure GitHub
  .github/.kodiak.toml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/labels.yml
  .github/stale.yml
  .github/workflows/ci-npm.yml
Labels: size/L
